# Generated by Django 5.2.11 on 2026-02-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='Top_Speed',
        ),
    ]
