# Generated by Django 5.2.11 on 2026-02-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_rename_make_car_top_speed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cars',
        ),
    ]
