# Generated by Django 5.2.11 on 2026-02-17 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_rename_car_cars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='BrandDb',
        ),
        migrations.CreateModel(
            name='CarsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('Top_Speed', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='Cars.branddb')),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
