# Generated by Django 5.2.11 on 2026-02-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_car_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
