# Generated by Django 5.2.11 on 2026-02-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Showroom',
        ),
    ]
